from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO
from PyPDF2 import PdfWriter, PdfReader
import json
import base64
import os

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def register(request):
    if request.method == "POST":
        username = request.POST['customer_name']
        mobile = request.POST['customer_mobile']
        email = request.POST['customer_email']
        password = request.POST['customer_password']
        
        # Create a new user
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()
        
        return redirect('login')  # Redirect to login page after successful registration
    return render(request, 'register.html')

def login(request):
    if request.method == "POST":
        mobile = request.POST['customer_mobile']
        user = User.objects.filter(username=mobile).first()

        password = request.POST['customer_password']

        
        user = authenticate(request, username=user.username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('index')  # Redirect to index page after successful login
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})
    return render(request, 'login.html')

@csrf_exempt
def generate_pdf(request):
    if request.method == "POST":
        data = json.loads(request.body)
        name = data["name"]
        dob = data["dob"]
        gender = data["gender"]
        aadhaar = data["aadhaar"]
        father = data["father"]
        address = data["address"]
        password = data["password"]
        img_data = data["imgData"]  # Base64-encoded image from html2canvas

        # Create PDF in memory
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4  # A4 dimensions in points (width=595, height=842)

        # Add header
        c.setFont("Helvetica-Bold", 16)
        c.drawCentredString(width / 2, height - 50, "Personal Identity Card")

        # Add details
        c.setFont("Helvetica", 12)
        text_y = height - 80
        c.drawString(50, text_y, f"Name: {name}")
        text_y -= 20
        c.drawString(50, text_y, f"Date of Birth: {dob}")
        text_y -= 20
        c.drawString(50, text_y, f"Gender: {gender}")
        text_y -= 20
        c.drawString(50, text_y, f"Aadhaar Number: {aadhaar}")
        text_y -= 20
        c.drawString(50, text_y, f"Father's Name: {father}")
        text_y -= 20
        c.drawString(50, text_y, f"Address: {address}")

        # Add ID card image
        img_data = img_data.split(",")[1]  # Remove "data:image/png;base64,"
        img_bytes = base64.b64decode(img_data)
        temp_img_path = "temp_id_card.png"
        with open(temp_img_path, "wb") as f:
            f.write(img_bytes)

        # Define fixed dimensions for the image (adjust as needed)
        img_width = 180
        img_height = 120  # Fixed height; adjust based on your ID card design
        c.drawImage(temp_img_path, 50, text_y - 130, width=img_width, height=img_height)

        # Add footer
        c.setFont("Helvetica", 10)
        c.drawString(50, 50, "Generated by eKYC Platform")

        c.showPage()
        c.save()

        # Encrypt the PDF
        pdf_writer = PdfWriter()
        pdf_reader = PdfReader(buffer)
        for page in pdf_reader.pages:
            pdf_writer.add_page(page)
        pdf_writer.encrypt(user_pwd=password, owner_pwd=None, use_128bit=True)

        # Write encrypted PDF to a new buffer
        encrypted_buffer = BytesIO()
        pdf_writer.write(encrypted_buffer)
        encrypted_buffer.seek(0)

        # Prepare response
        response = HttpResponse(encrypted_buffer.getvalue(), content_type="application/pdf")
        response["Content-Disposition"] = 'attachment; filename="personal-identity-card.pdf"'

        # Clean up
        buffer.close()
        encrypted_buffer.close()
        if os.path.exists(temp_img_path):
            os.remove(temp_img_path)

        return response

    return HttpResponse("Invalid request", status=400)
